/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BasicSettings: typeof import('./src/components/BasicSettings.vue')['default']
    BlueButtonGroup: typeof import('./src/components/BlueButtonGroup.vue')['default']
    BlueSelect: typeof import('./src/components/BlueSelect.vue')['default']
    BlueSlider: typeof import('./src/components/BlueSlider.vue')['default']
    BlueSwitch: typeof import('./src/components/BlueSwitch.vue')['default']
    ExpansibleOptions: typeof import('./src/components/ExpansibleOptions.vue')['default']
    ExpansiblePanel: typeof import('./src/components/ExpansiblePanel.vue')['default']
    ImageTab: typeof import('./src/components/ImageTab.vue')['default']
    OperationError: typeof import('./src/components/common/OperationError.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./src/components/Slider.vue')['default']
    SpinningLogo: typeof import('./src/components/common/SpinningLogo.vue')['default']
    StreamsTab: typeof import('./src/components/StreamsTab.vue')['default']
  }
}
