/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ImageTab: typeof import('./src/components/ImageTab.vue')['default']
    OperationError: typeof import('./src/components/common/OperationError.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./src/components/Slider.vue')['default']
    SpinningLogo: typeof import('./src/components/common/SpinningLogo.vue')['default']
    StreamsTab: typeof import('./src/components/StreamsTab.vue')['default']
  }
}
